### ISSUE TITLE
./swDMR: Permission denied

### ISSUE THREAD

**Issue by zhangaicen** [xflicsu/swDMR#1]
Dear Wu, 
 recently I tried used swDMR to identify DMRs of two samples from rice, but when install this software following the user guide, then run the software, it said  ./swDMR: Permission denied, I can't find what is wrong with it , so I copy the install process into the word ，could you help to solve this problem?  Thank you.
[permission denied.docx](https://github.com/xflicsu/swDMR/files/6256929/permission.denied.docx)

**Comment by xflicsu** [comment]
You can just change the file attribute with 'chmod 777 ./swDMR'.
Hope this help you.

> Dear Wu,
> recently I tried used swDMR to identify DMRs of two samples from rice, but when install this software following the user guide, then run the software, it said ./swDMR: Permission denied, I can't find what is wrong with it , so I copy the install process into the word ，could you help to solve this problem? Thank you.
> [permission denied.docx](https://github.com/xflicsu/swDMR/files/6256929/permission.denied.docx)

You can just change the file attribute with 'chmod 777 ./swDMR'.
Hope this help you.
